name: Install and Test LL on Linux

on:
  push:
    paths:
      - 'install_linux.sh'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0

    - name: Download and Install QQ Software
      run: |
        wget https://dldir1.qq.com/qqfile/qq/QQNT/c64ca459/linuxqq_3.2.5-20979_amd64.deb
        sudo dpkg -i linuxqq_3.2.5-20979_amd64.deb
        sudo apt-get install -f

    - name: Run install_linux.sh
      run: |
        chmod +x install_linux.sh
        ./install_linux.sh

    - name: Check output and directory existence
      run: |
        if ! /opt/QQ/qq --logging-enable | grep -q "[LiteLoader]" || [ ! -d "/opt/QQ/resources/app/LiteLoader/plugins" ]; then
          echo "LiteLoader not found in output or /opt/QQ/resources/app/LiteLoader/plugins directory does not exist. Test failed."
          exit 1
        else
          echo "LiteLoader found in output and /opt/QQ/resources/app/LiteLoader/plugins directory exists. Test succeeded."
        fi

    - name: Check LiteLoader Store
      run: |
        # 检查 LiteLoader 插件是否存在
        if [ -d "/opt/QQ/resources/app/LiteLoader/plugins/pluginStore" ]; then
          echo "LiteLoader pluginStore folder exists. Test succeeded."
        else
          echo "LiteLoader pluginStore folder does not exist. Test failed."
          exit 1
        fi

