name: Install and Test LL on macOS

on:
  push:
    paths:
      - 'install_mac.sh'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download and Install QQ Software
      run: |
        curl -LO https://dldir1.qq.com/qqfile/qq/QQNT/28615eb6/QQ_v6.9.25.20979.dmg
        hdiutil attach QQ_v6.9.25.20979.dmg
        cp -R /Volumes/QQ/QQ.app /Applications
        hdiutil detach /Volumes/QQ
        /Applications/QQ.app/Contents/MacOS/QQ &
    - name: Run install_mac.sh
      run: |
        chmod +x install_mac.sh
        ./install_mac.sh
        
    - name: Run QQ on macOS and check LiteLoader
      run: |
        USER_HOME="$HOME"
        if /Applications/QQ.app/Contents/MacOS/QQ && [ -d "$USER_HOME/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins" ]; then
          echo "LiteLoader found in output and LiteLoader plugins folder exists. Test succeeded."
        else
          echo "LiteLoader not found in output or LiteLoader plugins folder does not exist. Test failed."
          exit 1
        fi
