name: Install and Test LL on Windows

on:
  push:
    paths:
      - 'install_windows.py'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Install QQ Software
      run: |
        # Download QQ software
        Invoke-WebRequest -Uri 'https://dldir1.qq.com/qqfile/qq/QQNT/81d676ff/QQ9.9.7.20979_x64.exe' -OutFile QQInstaller.exe
        # Install QQ silently
        Start-Process -FilePath QQInstaller.exe -ArgumentList '/S' -Wait
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # 指定 Python 3 版本

    - name: Run install_windows.py
      run: |
        python3 install_windows.py

    - name: Run QQ with logging
      run: |
        "C:\Program Files\Tencent\QQNT\QQ" --enable-logging > qq_output.txt

    - name: Check output
      run: |
        # Use `type` to read the output file
        type qq_output.txt | findstr "[LiteLoader]" > nul
        if %errorlevel% neq 0 (
          echo "LiteLoader not found in output. Test failed."
          exit 1
        )