name: Install and Test LL on Windows

on:
  push:
    paths:
      - 'install_windows.py'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Install QQ Software
      run: |
        # Download QQ software
        Invoke-WebRequest -Uri 'https://dldir1.qq.com/qqfile/qq/QQNT/81d676ff/QQ9.9.7.20979_x64.exe' -OutFile QQInstaller.exe
        # Install QQ silently
        Start-Process -FilePath QQInstaller.exe -ArgumentList '/S' -Wait
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # 指定 Python 3 版本

    - name: Run install_windows.py
      run: |
        python3 install_windows.py

    - name: Run QQ with logging
      run: |
        start "C:\Program Files\Tencent\QQNT\QQ" --enable-logging

    - name: Check output
      run: |
        # Wait for a moment to let QQ start and generate logs
        Start-Sleep -Seconds 5
        # Get the process information for QQ
        $qqProcess = Get-Process -Name QQ -ErrorAction SilentlyContinue
        # Check if the process is running
        if ($qqProcess -ne $null) {
          # Check if LiteLoader is found in the process output
          $output = $qqProcess.MainModule.FileVersionInfo.InternalName
          if ($output -match "LiteLoader") {
            echo "LiteLoader found in process output. Test passed."
          } else {
            echo "LiteLoader not found in process output. Test failed."
            exit 1
          }
        } else {
          echo "QQ process not found. Test failed."
          exit 1
        }
